### ISSUE TITLE
Untested Scripts that I tested and WORK! :)

### ISSUE THREAD

**Issue by Scrubtasticx** [Loki1976/DOL-Custom-Scripts#4]
Here is a list of the untested scripts that work perfectly with newest branch of DOL
![Untitled](https://user-images.githubusercontent.com/1609846/54471176-48dd4e00-478b-11e9-92c2-10eb635a23c2.png)

**Comment by Scrubtasticx** [comment]
anything not in this picture from the untested directory in this branch tosses errors on start i will fix them this weekend and post when they are fixed,

**Comment by Loki1976** [comment]
Thank you
